# Generated by Django 4.1.4 on 2022-12-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='products',
            field=models.ManyToManyField(related_name='deli', to='products.products'),
        ),
        migrations.AlterField(
            model_name='deliveryunit',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
