# Generated by Django 4.1.4 on 2022-12-20 06:47

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_to),
        ),
    ]
