# Generated by Django 4.1.4 on 2022-12-21 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image_url',
        ),
    ]
